terraform {
  required_providers {
    digitalocean = { source = "digitalocean/digitalocean", version = "~> 2.0" }
    local        = { source = "hashicorp/local", version = "~> 2.0" }
  }
}
provider "digitalocean" { token = var.do_token }

locals {
  hosts     = var.hosts
  edge_host = "edge" # the single public host: WireGuard edge + Ansible controller + Gitea
}

# VPC + reserved IP live in the persistent `keep` module (survive `lab down`); passed in as vars.

# --- operator/ansible SSH key (generated by the orchestrator before apply) ---
resource "digitalocean_ssh_key" "op" {
  name       = "minilab2-op"
  public_key = file("${path.module}/${var.op_pubkey_file}")
}

# firewall-target tags (tag-based firewalls have no droplet-count limit)
resource "digitalocean_tag" "edge" { name = "ml2-edge" }
resource "digitalocean_tag" "private" { name = "ml2-private" }

# --- droplets ---
resource "digitalocean_droplet" "host" {
  for_each = local.hosts
  name     = each.key
  image    = "ubuntu-24-04-x64"
  size     = each.value.size
  region   = var.region
  vpc_uuid = var.vpc_id
  ssh_keys = [digitalocean_ssh_key.op.id]
  tags     = ["minilab2", "seg-${each.value.segment}", each.key == local.edge_host ? digitalocean_tag.edge.name : digitalocean_tag.private.name]
  user_data = templatefile("${path.module}/cloud-init.yaml.tftpl", {
    hostname          = each.key
    segment           = each.value.segment
    is_edge           = each.key == local.edge_host
    wg_server_privkey = each.key == local.edge_host ? var.wg_server_privkey : ""
    wg_client_pubkey  = each.key == local.edge_host ? var.wg_client_pubkey : ""
    vpc_cidr          = var.vpc_cidr
  })
}

# NOTE: the reserved-IP assignment is done by the orchestrator via doctl AFTER apply, not here.
# The digitalocean_reserved_ip_assignment resource intermittently fails its post-create read-back
# ("Provider produced inconsistent result ... Root object was present, but now absent"), which
# aborts the whole apply even though the assignment succeeded. doctl is idempotent and reliable;
# destroying the scm-ci droplet auto-unassigns the reserved IP (kept by the keep module).

# --- firewall: EDGE (scm-ci) — only the operator reaches WG + SSH; VPC east-west open ---
resource "digitalocean_firewall" "edge" {
  name = "minilab2-edge"
  tags = [digitalocean_tag.edge.name]

  inbound_rule { # WireGuard, operator only
    protocol         = "udp"
    port_range       = "51820"
    source_addresses = var.admin_cidrs
  }
  inbound_rule { # SSH admin, operator only
    protocol         = "tcp"
    port_range       = "22"
    source_addresses = var.admin_cidrs
  }
  inbound_rule { # intra-VPC east-west
    protocol         = "tcp"
    port_range       = "1-65535"
    source_addresses = [var.vpc_cidr]
  }
  inbound_rule {
    protocol         = "udp"
    port_range       = "1-65535"
    source_addresses = [var.vpc_cidr]
  }
  outbound_rule {
    protocol              = "tcp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "udp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "icmp"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}

# --- firewall: PRIVATE hosts — no public exposure; inbound only from the VPC ---
resource "digitalocean_firewall" "private" {
  name = "minilab2-private"
  tags = [digitalocean_tag.private.name]

  inbound_rule {
    protocol         = "tcp"
    port_range       = "1-65535"
    source_addresses = [var.vpc_cidr]
  }
  inbound_rule {
    protocol         = "udp"
    port_range       = "1-65535"
    source_addresses = [var.vpc_cidr]
  }
  inbound_rule {
    protocol         = "icmp"
    source_addresses = [var.vpc_cidr]
  }
  outbound_rule {
    protocol              = "tcp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "udp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "icmp"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}

# --- generated Ansible inventory (configure.sh regenerates this from live outputs too) ---
resource "local_file" "inventory" {
  filename        = "${path.module}/../../config/inventory/hosts.ini"
  file_permission = "0644"
  content = join("\n", concat(
    ["# GENERATED by terraform — do not edit", "[all:vars]", "ansible_user=root",
      "ansible_ssh_private_key_file=/opt/minilab2/op.key",
    "ansible_ssh_common_args=-o StrictHostKeyChecking=no", ""],
    [for g in distinct(flatten([for h in local.hosts : h.groups])) :
      join("\n", concat(["[${g}]"],
        [for k, h in local.hosts : "${k} ansible_host=${digitalocean_droplet.host[k].ipv4_address_private}" if contains(h.groups, g)],
      [""]))
    ]
  ))
}

output "vpn_endpoint" { value = var.reserved_ip }
output "edge_public_ip" { value = digitalocean_droplet.host[local.edge_host].ipv4_address }
output "host_private_ips" { value = { for k, h in digitalocean_droplet.host : k => h.ipv4_address_private } }
