variable "do_token" {
  type        = string
  description = "DigitalOcean API token (export TF_VAR_do_token=...)"
  sensitive   = true
}

variable "admin_cidrs" {
  type        = list(string)
  description = "CIDRs allowed to reach WireGuard(51820)+SSH(22) on the public host. During build: [build-box, player]. At handoff: [player]."
}

variable "region" {
  type    = string
  default = "nyc3"
}

variable "vpc_cidr" {
  type    = string
  default = "10.88.0.0/16"
}

variable "wg_server_privkey" {
  type      = string
  sensitive = true
}
variable "wg_client_pubkey" {
  type = string
}

variable "op_pubkey_file" {
  type        = string
  default     = "../../vpn/op.pub"
  description = "Operator/ansible SSH public key (generated by the orchestrator)."
}

# ---- Host inventory (mini-lab-02: 9 hosts, multi-team) ---------------------
# segment ∈ edge|scm|run|iac|plat|int ; size = DO slug ; groups = ansible groups.
# `edge` is the single PUBLIC host: WireGuard + Ansible controller + reverse proxy.
variable "hosts" {
  type = map(object({ segment = string, size = string, groups = list(string) }))
  default = {
    edge     = { segment = "edge", size = "s-1vcpu-2gb", groups = ["edge", "wireguard"] }
    gitea    = { segment = "scm", size = "s-2vcpu-4gb", groups = ["scm", "gitea"] }
    gitlab   = { segment = "scm", size = "s-4vcpu-8gb", groups = ["scm", "gitlab"] }
    runner   = { segment = "run", size = "s-2vcpu-4gb", groups = ["run", "gitea_runner", "gitlab_runner"] }
    atlantis = { segment = "iac", size = "s-2vcpu-4gb", groups = ["iac", "atlantis", "tf_exec"] }
    backend  = { segment = "plat", size = "s-2vcpu-4gb", groups = ["plat", "minio", "provider_mirror", "vault"] }
    registry = { segment = "plat", size = "s-1vcpu-2gb", groups = ["plat", "registry"] }
    k8s      = { segment = "int", size = "s-4vcpu-8gb", groups = ["int", "k3s", "argocd", "flux", "kyverno", "app_prod"] }
    siem     = { segment = "plat", size = "s-2vcpu-4gb", groups = ["plat", "siem"] }
  }
}

variable "vpc_id" {
  type        = string
  description = "VPC id from the keep module."
}
variable "reserved_ip" {
  type        = string
  description = "Reserved IP (stable VPN endpoint) from the keep module."
}
