#!/usr/bin/env bash
# configure.sh — run the config (Ansible) + seed layers. The Ansible CONTROLLER is `edge`
# (the single public host): we upload config/ + seed/ + the op SSH key there, install ansible,
# and run site.yml against the 9 hosts over the VPC. profile = trainer|realistic|insane.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE="${1:-realistic}"; MODE="${2:-}"
INFRA="$ROOT/infra/do"
OPKEY="$ROOT/vpn/op.key"
SSH="ssh -i $OPKEY -o StrictHostKeyChecking=no -o ConnectTimeout=15"

EDGE_IP="$(terraform -chdir="$INFRA" output -raw edge_public_ip)"
[ -n "$EDGE_IP" ] || { echo "no edge IP (run lab up first)"; exit 1; }

echo "[cfg] generating Ansible inventory from live terraform outputs"
mkdir -p "$ROOT/config/inventory"
terraform -chdir="$INFRA" output -json host_private_ips > "$ROOT/config/inventory/.ips.json"
INV_OUT="$ROOT/config/inventory/hosts.ini" python3 <<'PY'
import os, json
out = os.environ["INV_OUT"]
ips = json.load(open(os.path.join(os.path.dirname(out), ".ips.json")))
GROUPS = {
 "edge":     ["edge","wireguard"],
 "gitea":    ["scm","gitea"],
 "gitlab":   ["scm","gitlab"],
 "runner":   ["run","gitea_runner","gitlab_runner"],
 "atlantis": ["iac","atlantis","tf_exec"],
 "backend":  ["plat","minio","provider_mirror","vault"],
 "registry": ["plat","registry"],
 "k8s":      ["int","k3s","argocd","flux","kyverno","app_prod"],
 "siem":     ["plat","siem"],
}
groups = {}
for host, grps in GROUPS.items():
    if host not in ips: continue
    for g in grps: groups.setdefault(g, []).append(host)
with open(out, "w") as f:
    f.write("# GENERATED by configure.sh from terraform outputs\n")
    f.write("[all:vars]\nansible_user=root\nansible_ssh_private_key_file=/opt/minilab2/op.key\n")
    f.write("ansible_ssh_common_args=-o StrictHostKeyChecking=no\n\n")
    for g in sorted(groups):
        f.write("[%s]\n" % g)
        for h in sorted(groups[g]):
            f.write("%s ansible_host=%s\n" % (h, ips[h]))
        f.write("\n")
print("  wrote %d groups, %d hosts" % (len(groups), len(ips)))
PY

echo "[cfg] waiting for SSH to edge ($EDGE_IP)"
for i in $(seq 1 40); do $SSH root@"$EDGE_IP" true 2>/dev/null && break; sleep 5; done

echo "[cfg] waiting for cloud-init to finish on edge (releases the apt lock)"
$SSH root@"$EDGE_IP" 'command -v cloud-init >/dev/null && cloud-init status --wait >/dev/null 2>&1 || true'

echo "[cfg] installing ansible on the controller (edge)"
$SSH root@"$EDGE_IP" 'export DEBIAN_FRONTEND=noninteractive; apt-get update -y >/dev/null && apt-get install -y ansible rsync >/dev/null && ansible-galaxy collection install community.general ansible.posix community.postgresql >/dev/null 2>&1 || true'

echo "[cfg] uploading config/ + seed/ + op key"
$SSH root@"$EDGE_IP" 'mkdir -p /opt/minilab2'
scp -i "$OPKEY" -o StrictHostKeyChecking=no "$OPKEY" root@"$EDGE_IP":/opt/minilab2/op.key
$SSH root@"$EDGE_IP" 'chmod 600 /opt/minilab2/op.key'
rsync -az -e "$SSH" --delete "$ROOT/config/" root@"$EDGE_IP":/opt/minilab2/config/
rsync -az -e "$SSH" --delete "$ROOT/seed/"   root@"$EDGE_IP":/opt/minilab2/seed/ 2>/dev/null || true

if [ "$MODE" = "--reseed" ]; then
  echo "[cfg] re-running seed only (profile=$PROFILE)"
  $SSH root@"$EDGE_IP" "cd /opt/minilab2/seed && PROFILE=$PROFILE bash run-seed.sh" || echo "seed layer failed"
  exit 0
fi

echo "[cfg] running Ansible site.yml (profile=$PROFILE)"
$SSH root@"$EDGE_IP" "cd /opt/minilab2/config && ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook site.yml -e profile=$PROFILE"

echo "[cfg] running seed layer (profile=$PROFILE)"
$SSH root@"$EDGE_IP" "cd /opt/minilab2/seed && PROFILE=$PROFILE bash run-seed.sh" || echo "seed layer failed"
echo "[cfg] done"
